import type { Metadata } from "next";
import { Bricolage_Grotesque , Oswald} from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Galaxy fitness",
  description: "Generated by create next app",
};

const bricolageGrotesque = Bricolage_Grotesque({
  subsets:["latin"],
  variable:"--font-bricolage-grotesque",
})

const oswald = Oswald({
  subsets:["latin"],
  variable:'--font-oswald',

})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${bricolageGrotesque.variable} ${oswald.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
