import type { Metadata } from "next";
import { Bricolage_Grotesque , Oswald , Figtree} from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";

export const metadata: Metadata = {
  title: "Galaxy fitness",
  description: "Generated by create next app",
  icons: {icon:"/logo.png"}
};

const bricolageGrotesque = Bricolage_Grotesque({
  subsets:["latin"],
  variable:"--font-bricolage-grotesque",
})
const figtree = Figtree({
  subsets:["latin"],
  variable:'--font-figtree',
})

const oswald = Oswald({
  subsets:["latin"],
  variable:'--font-oswald',
})



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${bricolageGrotesque.variable} ${oswald.variable} ${figtree.variable} bg-background h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
      <Navbar/>
      {children}
      </body>
    </html>
  );
}
